apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: guestbook-staging:/Service:/guestbook-staging
  labels:
    app.kubernetes.io/instance: guestbook-staging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: guestbook-0.1.0
  name: guestbook-staging
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: guestbook-staging
    app.kubernetes.io/name: guestbook
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: guestbook-staging:apps/Deployment:/guestbook-staging
  labels:
    app.kubernetes.io/instance: guestbook-staging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: guestbook-0.1.0
  name: guestbook-staging
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: guestbook-staging
      app.kubernetes.io/name: guestbook
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: guestbook-staging
        app.kubernetes.io/name: guestbook
    spec:
      containers:
        - image: localhost:5111/gitops-demo-app:1.0.0
          imagePullPolicy: IfNotPresent
          name: guestbook
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
