# Production Environment Values
replicaCount: 3
revisionHistoryLimit: 5

image:
  repository: localhost:5000/gitops-demo-app
  tag: "2.0.0"
  pullPolicy: IfNotPresent

nameOverride: "gitops-demo"
fullnameOverride: "gitops-demo-guestbook"

service:
  type: NodePort
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 150m
    memory: 192Mi

# Environment variables to pass to the container
env:
  - name: APP_VERSION
    value: "2.0.0"
  - name: APP_ENVIRONMENT
    value: "prod"
