replicaCount: 1
revisionHistoryLimit: 3

image:
  repository: gcr.io/google-samples/kubernetes-bootcamp
  tag: "v1"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources: {}
