replicaCount: 1
revisionHistoryLimit: 3

image:
  repository: quay.io/argoprojlabs/argocd-e2e-container
  tag: "0.2"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources: {}
