# Production Environment Values
replicaCount: 3
revisionHistoryLimit: 5

image:
  repository: localhost:5000/gitops-demo-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

nameOverride: "gitops-demo"
fullnameOverride: "gitops-demo-guestbook"

service:
  type: NodePort
  port: 80
  targetPort: 8080

# Environment variables to pass to the container
env:
  - name: APP_VERSION
    value: "1.0.0"
  - name: APP_ENVIRONMENT
    value: "prod"
