# Staging Environment Values
replicaCount: 2
revisionHistoryLimit: 3

image:
  repository: localhost:5000/gitops-demo-app
  tag: "1.1.0"
  pullPolicy: IfNotPresent

nameOverride: "gitops-demo"
fullnameOverride: "gitops-demo-guestbook"

service:
  type: NodePort
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Environment variables to pass to the container
env:
  - name: APP_VERSION
    value: "1.1.0"
  - name: APP_ENVIRONMENT
    value: "staging"
