replicaCount: 1
revisionHistoryLimit: 3

image:
  repository: localhost:5111/gitops-demo-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 8080

resources: {}
