apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: guestbook-prod:/Service:/guestbook-prod
  labels:
    app.kubernetes.io/instance: guestbook-prod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: guestbook-0.1.0
  name: guestbook-prod
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: guestbook-prod
    app.kubernetes.io/name: guestbook
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: guestbook-prod:apps/Deployment:/guestbook-prod
  labels:
    app.kubernetes.io/instance: guestbook-prod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: guestbook-0.1.0
  name: guestbook-prod
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: guestbook-prod
      app.kubernetes.io/name: guestbook
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: guestbook-prod
        app.kubernetes.io/name: guestbook
    spec:
      containers:
        - env:
            - name: APP_VERSION
              value: 1.0.0
            - name: APP_ENVIRONMENT
              value: prod
          image: localhost:5111/gitops-demo-app:1.0.0
          imagePullPolicy: IfNotPresent
          name: guestbook
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
