apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated: {}
  sourceHydrator:
    drySource:
      repoURL: https://github.com/wdbetts/gitops-promotion-demo.git
      targetRevision: HEAD
      path: helm-guestbook
      helm:
        valueFiles:
          - values-dev.yaml
    syncSource:
      targetBranch: environments/dev
      path: helm-guestbook
