apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-prod
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated: {}
  sourceHydrator:
    drySource:
      repoURL: https://github.com/wdbetts/gitops-promotion-demo.git
      targetRevision: environments/staging # This is the branch where the prod environment is based on
      path: env-configs/prod
    syncSource:
      targetBranch: environments/prod
      path: env-configs/prod
